replicaCount: 2

image:
  repository: thilina123/employee-management-system-frontend
  tag: 35
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-secret

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30090

containerPort: 80