apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ems-frontend               
  template:
    metadata:
      labels:
        app: ems-frontend
    spec:
      containers:
        - name: ems-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}